runtime: python313
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app

env_variables:
  USERNAME: "admin"
  PASSWORD_HASH: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"  # SHA256 of "password"
  JWT_SECRET_KEY: "change-this-to-a-secure-random-string-in-production"
  AES_KEY_HASH: "replace-with-actual-sha256-hash"  # For Phase 3
  GCP_PROJECT: "replace-with-project-id"
  GCS_BUCKET: "replace-with-bucket-name"

automatic_scaling:
  min_instances: 0
  max_instances: 10